{% set name = "eth-account" %}
{% set version = "0.12.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/eth_account-{{ version }}.tar.gz
  sha256: 202cc886d0480b4d95e702c24796d9b03e5b328070d5b1bc5641b849dd21acbd

build:
  number: 0
  noarch: python
  script: python -m pip install . -vv

outputs:
  - name: eth-account
    build:
      noarch: python
    requirements:
      host:
        - pip
        - python {{ python_min }}
        - setuptools
      run:
        - python >={{ python_min }}
        - bitarray >=2.4.0
        - eth-abi >=4.0.0b2
        - eth-keyfile >=0.6.0
        - eth-keys >=0.4.0
        - eth-rlp >=2.1.0
        - eth-utils >=2.0.0
        - hexbytes >=1.2.0
        - rlp >=1.0.0
        - ckzg >=0.4.3
        - pydantic >=2.0.0
    test:
      requires:
        - pip
      commands:
        - pip check
      imports:
        - eth-account

  - name: eth_account
    build:
      noarch: python
    requirements:
      run:
        - {{ pin_subpackage('eth-account', max_pin="x.x.x") }}
    test:
      imports:
        - eth_account


about:
  home: https://github.com/ethereum/eth-account
  summary: 'eth-account: Sign Ethereum transactions and messages with local private keys'
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - step21
