{% set name = "eth-account" %}
{% set version = "0.12.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0374c5886f35780e1f23e50ce6b0482f3387646eceda544e97d69f17f6c216ee

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7,<4.0
  run:
    - python >=3.6,<4.0
    - bitarray >=2.4.0
    - eth-abi >=4.0.0b2
    - eth-keyfile >=0.6.0
    - eth-keys >=0.4.0
    - eth-rlp >=0.3.0
    - eth-utils >=2.0.0
    - hexbytes >=0.1.0,<0.4.0
    - rlp >=1.0.0

test:
  imports:
    - eth_account
    - eth_account._utils
  requires:
    - pip

about:
  home: https://github.com/ethereum/eth-account
  summary: 'eth-account: Sign Ethereum transactions and messages with local private keys'
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - step21
